language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
install:
    - pip install zope.testing --use-mirrors
script:
    - python setup.py test -q

# Just a note that this is possible:
##notifications:
##  irc:
##    channels: "irc.freenode.org#zope-dev"
##    on_success: change
##    on_failure: change
##  email:
##    - zope-tests@zope.org
